From: https://www.matecdev.com/posts/julia-tutorial-science-engineering.html#google_vignette

Note that there is more array functionality in packages such as LinearAlgebra.jl, StaticArrays.jl, and SparseArrays.jl.

In [ ]:
# Direct input
A = [1 2 3; 1 2 4; 2 2 2]     # 3×3 Matrix{Float64}
A = [1 2 3;                   # 3×3 Matrix{Float64}
     1 2 4;
     2 2 2]     
b1 = [4.0, 5, 6]              # 3-element Vector{Float64}
b2 = [4.0; 5; 6]              # 3-element Vector{Float64}
m1 = [4.0 5 6]                # 1×3 Matrix{Float64}
A = ["Hello", 1, 2, 3]        # Vector of type Any

### Array comprehension vs. generators

A very concise way to initialize and array is by resorting to so-called array comprehensions.
The following code builds an array with the first 100,000 terms of a quadratic series, and then performs the sum.

When using parenthesis instead of the square brackets, Julia will produce a slightly different object: a generator. Generators can be iterated to produce the required values when needed.
As the underlying array isn’t allocated in memory in advance, the generator could have better performance than the array comprehension.

In [ ]:
# Array comprehensions
v = [1/n^2 for n=1:100000]
x = sum(v)

In [ ]:
# Array generators
gen = (1/n^2 for n=1:100000)
x = sum(gen)

### Undefined arrays
For performance reasons, it is wise to initialize arrays of a given type (and size), without specifying any values.  To do this, we can employ keywords such as Vector{T}, Matrix{T} or Array{T}, where T is a type (see, for example, Numeric Types in the documentation).

The reason to declare undefined arrays is to be able to fill them later — for example, with the use of a for loop.

What happens under the hood when we declare an undef array, is that a certain portion of memory gets reserved (or allocated) for this specific use. As the computer is not even filling that chunk of memory with zeros, we are saving some time.

In [ ]:
n = 5
A1 = Array{Float64}(undef,n,n)          # 5×5 Matrix{Float64}
A2 = Matrix{Float64}(undef,n,n)         # 5×5 Matrix{Float64}

V1 = Array{Float64}(undef,n)            # 5-element Vector{Float64}
V2 = Vector{Float64}(undef,n)           # 5-element Vector{Float64}

A = Array{String}(undef,n)
A = Array{Any}(undef,n)

### Empty arrays
Empty arrays can be a useful starting point when we are in a situation where it is hard or impossible to know which array sizes we need in advance. An empty array can be later grown dynamically, and filled with values. (see the “Dynamic Arrays” section below in this page).

To initialize an empty array, it is perfectly valid to use n = 0 in the above expressions.


To initialize an empty array, it is perfectly valid to use n = 0 in the above expressions. There is a shorthand for this expression: (see second line). A possible source of errors would be to confuse this array with an empty array of “Any” type, which is initialized as follows: (see third line). If we later fill this array dynamically with Float values, its type would remain fixed at “Any”, which could lead to bad performance — or even errors, if we plan on passing this array to a function which requires arrays of type Float, for example.

In [1]:
v = Array{Float64}(undef,0)     
v = Float64[]                # shorthand for above expression
v = []    # Same as Any[], and you can't change this type easily later (gotcha!)

Any[]

### Special kinds of arrays
See Documentation for lots of examples: https://docs.julialang.org/en/v1/manual/arrays/#Construction-and-Initialization

In [ ]:
A = zeros(8,9)
B = ones(8,9)
C = rand(6,6)

In the case of the identity matrix, placing an integer right before a letter ‘I’ will do the job, but this requires the LinearAlgebra package:

In [2]:
using LinearAlgebra
M = 5I + rand(2,2)

2×2 Matrix{Float64}:
 5.26008    0.837589
 0.0847017  5.89708

### Applying a scalar function to an array and broadcasting the dot operator
It often happens that we have a function which can be applied to a scalar number, but we want to apply it to an array. Of course, we could resort to a for loop to this element-wise function application. But that would be too much hassle.

Fortunately, in Julia we can easily turn a function than accepts a scalar value, and apply it element-wise to an array. The way to do this is to employ a ‘dot’ after the function’s name.

For example, let’s define a scalar function f, and apply it to an array.

In [3]:
f(x) = 3x^3/(1+x^2)
x = [2π/n for n=1:30]
y = f.(x)

y = sin.(x) # dot operator is also needed for common arithmetic and trigonometric functions
y = 2x.^2 + 3x.^5 - 2x.^8
y = @. 2x^2 + 3x^5 - 2x^8   # We can also broadcast the dot operator with @

30-element Vector{Float64}:
     -4.828671033653536e6
 -18039.263768983117
   -610.7857528421777
    -40.50500091388652
      0.12239075156841928
      3.0788623155395416
      2.5165970179806223
      1.8406756088311296
      1.3594357907060943
      1.0347659706787375
      0.812285884726568
      0.6550760528496817
      0.5403678534183181
      ⋮
      0.23029553231945027
      0.20638290794502417
      0.1861052313390679
      0.16874585207464307
      0.15375911701431397
      0.14072317776024484
      0.12930739401638117
      0.1192493881563927
      0.11033861036842828
      0.10240437795375669
      0.09530704253783058
      0.08893137900051265

### Array indexing

In [ ]:
A = rand(6)
A[begin]        # get first element
A[end]          # get last element

### Array slicing
The code below will extract the odd indices in both dimensions from a 6x6 matrix, and store the results in a new 3x3 matrix.

In [ ]:
A = rand(6,6)                   # 6×6 Matrix{Float64}
B = A[begin:2:end,begin:2:end]  # 3×3 Matrix{Float64}
C = A[1:2:5,1:2:5]              # Same as B

### Logical indexing
Let's generate an array of random numbers and set to 0 all the elements with values below 0.5

In [7]:
A = rand(6,6)
display(A)
A[A .< 0.5 ] .= 0
A

6×6 Matrix{Float64}:
 0.378289  0.867453  0.70299    0.281435  0.746615   0.371353
 0.244027  0.592541  0.0840049  0.080798  0.286068   0.193589
 0.922705  0.450322  0.964589   0.067477  0.0179448  0.524227
 0.727674  0.848769  0.996467   0.388537  0.253183   0.715831
 0.940938  0.965446  0.315638   0.340858  0.234497   0.603208
 0.955896  0.270209  0.726826   0.081712  0.899792   0.311369

6×6 Matrix{Float64}:
 0.0       0.867453  0.70299   0.0  0.746615  0.0
 0.0       0.592541  0.0       0.0  0.0       0.0
 0.922705  0.0       0.964589  0.0  0.0       0.524227
 0.727674  0.848769  0.996467  0.0  0.0       0.715831
 0.940938  0.965446  0.0       0.0  0.0       0.603208
 0.955896  0.0       0.726826  0.0  0.899792  0.0

### Iterating over an Array

In [8]:
# Iterating over single dimensional arrays
A = rand(6)
for i ∈ eachindex(A)
    println(string("i=$(i) A[i]=$(A[i])"))
end

i=1 A[i]=0.22575419280357356
i=2 A[i]=0.6361297179363737
i=3 A[i]=0.7181026222435212
i=4 A[i]=0.8176338126037256
i=5 A[i]=0.2931970923395437
i=6 A[i]=0.41650794809424563


In [9]:
# Iterating over multi-dimensional arrays
A = rand(6,6)
for i ∈ 1:size(A,1), j ∈ 1:size(A,2)
    println(string("i=$(i) j=$(j) A[i,j]=$(A[i,j])"))
end

i=1 j=1 A[i,j]=0.34313165581473715
i=1 j=2 A[i,j]=0.8013939382764056
i=1 j=3 A[i,j]=0.41958782057273547
i=1 j=4 A[i,j]=0.9762289134455772
i=1 j=5 A[i,j]=0.11362555229938798
i=1 j=6 A[i,j]=0.20018579611350928
i=2 j=1 A[i,j]=0.57847820866286
i=2 j=2 A[i,j]=0.4251761316871516
i=2 j=3 A[i,j]=0.9495758752377109
i=2 j=4 A[i,j]=0.4122194928154801
i=2 j=5 A[i,j]=0.5380901686295511
i=2 j=6 A[i,j]=0.47789411969966566
i=3 j=1 A[i,j]=0.47881454823195146
i=3 j=2 A[i,j]=0.4366184593777004
i=3 j=3 A[i,j]=0.5539116755809569
i=3 j=4 A[i,j]=0.23201657247107632
i=3 j=5 A[i,j]=0.26599970281293595
i=3 j=6 A[i,j]=0.7879526755201003
i=4 j=1 A[i,j]=0.20796917774503587
i=4 j=2 A[i,j]=0.3169290316728107
i=4 j=3 A[i,j]=0.32749249684180337
i=4 j=4 A[i,j]=0.6993421293450947
i=4 j=5 A[i,j]=0.4705595037449738
i=4 j=6 A[i,j]=0.03699903958801565
i=5 j=1 A[i,j]=0.3052685744564301
i=5 j=2 A[i,j]=0.3888917565470179
i=5 j=3 A[i,j]=0.2585719774070795
i=5 j=4 A[i,j]=0.485368171238428
i=5 j=5 A[i,j]=0.25512311580205727
i=5 j

In [16]:
# Iterating over multidimensional arrays which may not be 1-indexed
A = rand(6,6)
for i ∈ axes(A,1), j ∈ axes(A,2)
    println(string("i=$i j=$j A[i,j]=$(A[i,j])")) # the parentheses are needed to apply $ to all of the expression A[i,j]
end

i=1 j=1 A[i,j]=0.1894169923794038
i=1 j=2 A[i,j]=0.551803812895888
i=1 j=3 A[i,j]=0.5914632118609555
i=1 j=4 A[i,j]=0.8632060891545584
i=1 j=5 A[i,j]=0.45197688061832897
i=1 j=6 A[i,j]=0.029354093896227562
i=2 j=1 A[i,j]=0.16560821411149307
i=2 j=2 A[i,j]=0.15479244518293944
i=2 j=3 A[i,j]=0.6580092046928492
i=2 j=4 A[i,j]=0.7770820876624438
i=2 j=5 A[i,j]=0.3768538933953566
i=2 j=6 A[i,j]=0.5781940399440307
i=3 j=1 A[i,j]=0.0892378950139342
i=3 j=2 A[i,j]=0.4369320861055124
i=3 j=3 A[i,j]=0.9597788866861444
i=3 j=4 A[i,j]=0.08063710681181557
i=3 j=5 A[i,j]=0.5479275949196152
i=3 j=6 A[i,j]=0.5761873362818914
i=4 j=1 A[i,j]=0.8354341887389534
i=4 j=2 A[i,j]=0.10855620610226169
i=4 j=3 A[i,j]=0.636722088819091
i=4 j=4 A[i,j]=0.4273262487016469
i=4 j=5 A[i,j]=0.8540178747503135
i=4 j=6 A[i,j]=0.04122563399157897
i=5 j=1 A[i,j]=0.23291847541233868
i=5 j=2 A[i,j]=0.5592808806119711
i=5 j=3 A[i,j]=0.6236766345619291
i=5 j=4 A[i,j]=0.753042801046372
i=5 j=5 A[i,j]=0.8813395369089645
i=5 j=6 

### Basic operations of multidimensional arrays (i.e. matrix multiplication, dot product)

Matrices (two dimensional arrays) can be multiplied with Matlab-style syntax (* operator). A Matrix and vector can also be multiplied with the (*) operator.

In [17]:
A = [1 2 3; 1 2 4; 2 2 2]
B = [1 2 3; 1 2 4; 2 2 2]   # A*B allowed
v = [4.0, 5, 6]             # A*v allowed
m1 = [4.0 5 6]              # A*m1 not allowed

1×3 Matrix{Float64}:
 4.0  5.0  6.0

### Element-wise multiplication
The dot operator will broadcast the scalar multiplicaion operator on an element-wise fashion.

In [22]:
A.*B

3×3 Matrix{Int64}:
 1  4   9
 1  4  16
 4  4   4

### Dot product

In [23]:
v = rand(1000)
w = rand(1000)
z = dot(v,w)
z = v'w     # Typical linear algebra notation
# I guess ' is transpose?

252.494560573598

### Backslash operator
Like in Matlab, this is a built-in operator to solve matrices. For square matrices, it will try to solve the linear system. For rectangular matrices, it will see the least squares solution. (WHAT DOES THAT MEAN?)

One GOTCHA you may encounter is that, since 1xN matrices are not the same as N-element vectors, we have to be careful and always employ vectors in the right-hand side of an equation.

In [29]:
b1 = [4.0, 5, 6]        # 3-element Vector{Float64}
b2 = [4.0; 5; 6]        # 3-element Vector{Float64}
m1 = [4.0 5 6]          # 1x3 Matrix{Float64}

x=A\b1                  # Solves A*x=b
x=A\b2                  # Solves A*x=b
#x=A\m1                  # Error!!

3-element Vector{Float64}:
  3.0
 -1.0
  1.0

### Resizing and concatenating arrays
Let's start with default dynamic array operations in Julia. By default, arrays in Julia are Dynamic (e.g. growable, resizable) unless defined otherwise.

In [30]:
# Resizing 1D arrays with Push and Pop
A = Float64[]       # Equivalent to A=Array{Float64}(undef, 0)
push!(A,4)          # Adds the number 4 at the end of the array
push!(A,3)          # Adds the number 3 at the end of the array
v = pop!(A)         # Returns 3 and removes it from A

3.0

In [34]:
pushfirst!(A, 5)
A
v = popfirst!(A)

5.0

In [44]:
A = Float64[]       # Equivalent to A=Array{Float64}(undef, 0)
push!(A,4)
pushfirst!(A, 5)
v = splice!(A, 2)
println(v)
A

4.0


1-element Vector{Float64}:
 5.0

In [41]:
A = Float64[]       # Equivalent to A=Array{Float64}(undef, 0)
push!(A,4)
pushfirst!(A, 5)
deleteat!(A, 2)
A

1-element Vector{Float64}:
 5.0

### Multi-dimensional Array Concatenation

In [47]:
# hcat and vcat work for 2D arrays and below
A = [4 5 6]
B = [6 7 8]

M1 = vcat(A,B)
display(M1)
M2 = hcat(A,B)
display(M2)

# same result can be accomplished with syntax for inputting a matrix
M1 = [A; B]
M2 = [A B]

2×3 Matrix{Int64}:
 4  5  6
 6  7  8

1×6 Matrix{Int64}:
 4  5  6  6  7  8

In [49]:
# The cat function can also work for n-dimensional arrays
M1 = cat(A, B, dims=1)
display(M1)
M2 = cat(A, B, dims=2)
display(M2)
M3 = cat(A, B, dims=3)
display(M3)

2×3 Matrix{Int64}:
 4  5  6
 6  7  8

1×6 Matrix{Int64}:
 4  5  6  6  7  8

1×3×2 Array{Int64, 3}:
[:, :, 1] =
 4  5  6

[:, :, 2] =
 6  7  8

In [51]:
# Concatenating vectors (different from 1xn matrices!)
a = [1, 2, 3]
b = [4, 5, 6]
# hcat and vcat have the opposite effect from before
v1 = vcat(a, b)
display(v1)

v2 = hcat(a,b)
display(v2)

# equivalently
v1 = [a b] # spaces equivalent to hcat
v2 = [a; b] # semicolons equivalent to vcat

# vector of vectors (concatenate using commas)
v3 = [a,b]
display(v3)

# stack function will concatenate a vector of vectors along a specified dimensional
s1 = stack([a,b], dims=1) # results in 2x3 matrix
display(s1)
s2 = stack([a,b], dims=2) # results in 3x2 matrix
display(s2)

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

2-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5, 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

## Functions
Since Julia is JIT compiled, you need to wrap your code inside a function in order to get it compiled. Thus, performance-critical sections of code should always be written inside functions.

In [53]:
# Single line function definition
sum_zeta(s,nterms) = sum(1/n^s for n=1:nterms)

println(sum_zeta(2))

# Multi-line function definition
function sum_zeta(s,nterms)
    x = 0
    for n in 1:nterms
        x = x + (1/n)^s
    end
    return x
end

println(sum_zeta(2, 10000)) # Notice slightly lower precision

1.6448340718480652
1.64493306684877


### Keyword arguments and optional arguments
Keyword arguments are identified by name rather than by position. Their syntax is very similar to optional arguments, with the only difference being that they are placed after a semicolon in the function definition. Notice there can be a slight difference in the precision of your answers depending on whether you enter the value `10000` or `1e6`

In [58]:
sum_zeta1(s, nterms=10000) = sum(1/n^s for n=1:nterms) # nterms optional argument
sum_zeta2(s; nterms=10000) = sum(1/n^s for n=1:nterms) # nterms keyword argument

println(sum_zeta1(2))
println(sum_zeta1(2, 10000)) # same as above
#println(sum_zeta1(2, nterms=10000)) # error! not a keyword

println(sum_zeta2(2))
#println(sum_zeta2(2, 10000)) # error! need a keyword
println(sum_zeta2(2, nterms=10000))
println(sum_zeta2(2, nterms=1e6)) # notice difference in precision

1.6448340718480652
1.6448340718480652
1.6448340718480652
1.6448340718480652
1.64493306684877


### Functions with multiple outputs
When you have a function that returns multiple outputs, what is happening under the hood is that the function is returning a `tuple` and the `tuple` is being destructured into two variables. We can also call for a single output and destructure is ourselves (see `shape` below). Note that tuples are immutable structures, so we won't be able to modify the values of `shape`, but we can modify the values of `a` and `c`.

In [64]:
function circle(r)
    area = π * r^2
    circumference = 2π * r
    return area, circumference
end

a1, c1 = circle(1.5) # save outputs destructured as variables
println(a1, "\n", c1)

shape = circle(1.5) # save tuple of outputs, destructure them ourselves
a2, c2 = shape
println(a2, "\n", c2)


7.0685834705770345
9.42477796076938
7.0685834705770345
9.42477796076938


### Functions which modify their input (! notation, aka bang! notation)
It is convention to append an exclamation mark to names of functions that modify their arguments. Note that not every type of variable can be modified by a function when passed as an input: the variable has to be *mutable*. `Arrays` are mutable by default. `Tuples` are not. If you pass an immutable variable type to `x`, the value of the variable `x` will change only inside the function `add_one`, but the process won't affect the value of `x` outside of the function.

Note that bang! notation is also used in the `Plots.jl` visualization library to add more data to an existing `plot` object.

In [ ]:
function add_one!(x)
    x .= x .+ 1
end

x = [1,2,3]
add_one!(x); # x is now [2,3,4]

### Anonymous functions
Sometimes we don't need to assign a name to a function. For instance, if we just need to quickly define a function in order to pass it as an argument to another function, then anonymity can come in handy. 

Suppose we are using the following function `secant` which finds the root of a given function `f` using the secant method. This can be applied to any function `f`. So, we could either define a function for `f` and pass it as an argument, OR we could use anonymous function as shorthand. (That's the `x -> x^2 - x - 1`) below.

In [65]:
function secant(f,a,b,rtol,maxIters)
    iter = 0
    while abs(b-a) > rtol*abs(b) && iter < maxIters
        c,a = a,b
        b = b + (b-c)/(f(c)/f(b)-1)
        iter = iter + 1
    end
    return b
end

φ = secant( x-> x^2 - x - 1, 1, 2, 1e-15, 10 )

1.6180339887498947